
DROP TABLE IF EXISTS works;
DROP TABLE IF EXISTS checkpoints;
DROP TABLE IF EXISTS projects;

CREATE TABLE "projects"
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                            VARCHAR(255),
    number                          VARCHAR(255),
    condition                       VARCHAR(255) check (condition in ('FORMING','APPROVING','REFINEMENT','IMPLEMENTATION','FINISHED')),
    average_completion_percentage   FLOAT(53),
    director                        VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE if NOT EXISTS "checkpoints"
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    finish_date         TIMESTAMP(6),
    project_id          BIGINT REFERENCES projects(id),
    PRIMARY KEY (id),
    UNIQUE (name, project_id)
);

CREATE TABLE if NOT EXISTS "works"
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                            VARCHAR(255),
    start_date                      TIMESTAMP(6),
    finish_date                     TIMESTAMP(6) check (finish_date >= start_date),
    average_completion_percentage   FLOAT(53),
    implementer                     VARCHAR(255),
    project_id                      BIGINT REFERENCES projects(id),
    checkpoint_id                   BIGINT REFERENCES checkpoints(id),
    PRIMARY KEY (id)
);
